redis:
  persist:
    weather-data:
      timeout: 1800

quartz:
  job:
    weather-collector:
      corn: 0 */15 * * * ?

itzone123:
  api:
    version: 1.1

---
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: itzone123
    password: 123
    virtual-host: itzone123-vhost

---
spring:
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0